# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  variables: 
    env : deewar
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob $(runman) $(env)
  - job: Secondjob
    steps:
    - bash: echo Build Secondjob  $(env)
- stage: Test
  dependsOn: Build
  jobs:
    - job: TestJob
      steps:
      - bash: echo Build TestJob $(env)
- stage: Deploy
  dependsOn: Test
  jobs:
    - job: DeployJob
      steps:
      - bash: echo DeployJob  
    
